name: docker build
on:
  push:
    branches:
      - gh-jeep
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - uses: action/setup-node@v2
        with:
          node-version: '12'
      - run: npm install
      - run: npm test
      - run: docker build -t ihavebuild:v1 .
